
MAX_EPOCH = 9999999999
RULE_GAP_LAST = 1
RULE_GAP_NULL = 2
RULE_GAP_INTERPOLATE = 3
RULE_GAP_CONSTANT = 4
DP_STATUS_OK = 0
DP_STATUS_ESTIMATED = 1
DP_STATUS_LAST = 2
DP_STATUS_NULL = 3
DP_STATUS_CONSTANT = 4
DP_STATUS_OVERFLOW = -1
DP_STATUS_UNDERFLOW = -2
DP_STATUS_GAP = -3
DP_STATUS_INCREMENT = -4
DP_STATUS_DECREMENT = -5
DP_STATUS_UNKNOWN = -6
TS_TS = 0
TS_VALUE = 1
TS_STATUS = 2

JOB_TYPE_HOUR = 0
JOB_TYPE_DAY = 1
JOB_TYPE_MONTH = 2
JOB_TYPE_YEAR = 3

